dataset:
  path: ./data

training:
  seed: 39
  device: cuda:0

  # Whether ot overfit single batch of 4 images during 100 epochs.
  overfit_single_batch: true

  # Whether to exclude background class from target segmentation masks?
  # NOTE: DON'T FORGET TO CHANGE n_classes IN MODEL SECTION IF YOU SET THIS TO True!
  exclude_background_class: true

  epochs: 10
  cache:
    - masks
    - images
  image_size: 224
  batch_size: 20
  dataloader_num_workers: 6

model:
  n_classes: 20
  transplant_score_layer: true
  init_upsampling_as_bilinear: true

# As in paper.
optimizer:
  __class_fullname__: torch.optim.SGD
  lr: 0.0001
  weight_decay: 0.0002
  momentum: 0.9

criterion:
  __class_fullname__: torch.nn.BCEWithLogitsLoss

augmentations:
  train:
    transform:
      __class_fullname__: Compose
      transforms:

        # To PyTorch tensors.
        - __class_fullname__: Normalize
          always_apply: true
          max_pixel_value: 255.0
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
        - __class_fullname__: ToTensorV2
          transpose_mask: true
          always_apply: true
      additional_targets: {'image': 'image', 'mask': 'mask'}
  val:
    transform:
      __class_fullname__: Compose
      transforms:

        # To PyTorch tensors.
        - __class_fullname__: Normalize
          always_apply: true
          max_pixel_value: 255.0
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
        - __class_fullname__: ToTensorV2
          transpose_mask: true
          always_apply: true
      additional_targets: {'image': 'image', 'mask': 'mask'}